"""Bars and tape - the guess a candle forces, and the answer the trades hold.

A bracket puts two levels around a position. When a bar's range covers both,
the OHLC cannot say which one traded first: high and low carry no order. The
engine has to assume, and it assumes the stop, because that is the conservative
reading. Assuming is not knowing, and this file measures the gap.

One dataset, two resolutions. A tape is generated once, `tape_to_bars`
aggregates it into the engine's own bar schema, and the bar engine runs on
those bars. Every trade it books is then put back to the tape it came from,
which knows the sequence. Nothing is aligned, joined or approximated: the bars
ARE the tape, summarised.

What comes out:

  1. how many exits the bar engine had to guess at;
  2. how often the guess was wrong;
  3. what the wrong guesses cost, in the only currency that matters.

The conservative assumption is not free: every time it is wrong it books a loss
the trade never took, and here those phantom losses are several times the whole
reported return.

Demonstrates:
  - `bt.ticks.tape_to_bars`: a tape as a drop-in bar dataset
  - the same bracket resolved by a candle and by the trades inside it
  - `bt.ticks.simulate_brackets(...)`: the whole trade log re-asked in one
    Rust call - the tape read once, every bracket resolved in parallel

NOT RUNNABLE YET. The tick layer (`bt.ticks`) is not unlocked by any licence
sold today, a Pro one included: the code ships ahead of its availability, so
this file is here to be READ. It will run when the layer opens; nothing in it
is a placeholder, and the numbers it prints are the ones it will print then.

Requires pandas as well, alone among the files here: the comparison below
re-indexes the bars by timestamp and joins the trade log against them, which
is a DataFrame's job. `pip install manifoldbt[pandas]`.

Data: synthetic (seed 20260827) - generated by this file, reproducible.
The fixture is a plain random walk with no drift, so the DIRECTION of the gap
is meaningful and its size is not a forecast of any real market.

Usage:
    python examples/27_bars_vs_tape.py
"""

import os
import tempfile

import numpy as np

try:
    import pandas  # noqa: F401  -- see the header: the join below needs it
except ModuleNotFoundError:
    raise SystemExit(
        "27_bars_vs_tape.py reads its results with pandas, which the engine "
        "does not depend on. Install it with: pip install manifoldbt[pandas]"
    )

import manifoldbt as mbt
from manifoldbt.helpers import Interval, Slippage
from manifoldbt.indicators import close, sma

# -- The dataset: one tape, then the bars it summarises -----------------------
SEED = 20260827
N_TICKS = 400_000
BAR_SECONDS = 60
SL_PCT, TP_PCT = 0.6, 0.6          # symmetric, so neither level is favoured


def build_dataset(root):
    """Generate a tape, aggregate it into bars, return (tape path, store)."""
    tape = os.path.join(root, "tape.csv")
    mbt.ticks.generate_tape(
        tape,
        seed=SEED,
        n_ticks=N_TICKS,
        # ~120 ms between trades gives a tape long enough for ~800 one-minute
        # bars, and a per-tick volatility that moves price through a 0.6%
        # bracket often enough to produce contested bars.
        mean_gap_ms=120.0,
        vol_per_tick=0.00035,
        drift_per_tick=0.0,
        start_price=100.0,
    )
    batch = mbt.ticks.tape_to_bars(tape, BAR_SECONDS, symbol_id=1)
    frame = batch.to_pandas()
    store = mbt.import_dataframe(
        frame[["timestamp", "open", "high", "low", "close", "volume"]],
        symbol="TAPE", symbol_id=1, interval="1m",
        data_root=os.path.join(root, "data"),
        metadata_db=os.path.join(root, "meta.sqlite"),
    )
    return tape, store, frame


# -- The strategy: an ordinary bracket, nothing exotic ------------------------
strategy = (
    mbt.Strategy.create("bracketed")
    .signal("fast", sma(close, 5))
    .signal("slow", sma(close, 30))
    .size(mbt.when(sma(close, 5) > sma(close, 30), 1.0, 0.0))
    .stop_loss(SL_PCT)
    .take_profit(TP_PCT)
    .describe("Long the crossover, leave on whichever bracket level trades first")
)


def config_for(frame):
    last = int(frame["timestamp"].iloc[-1].value)
    return mbt.BacktestConfig(
        universe=[1],
        time_range_start=0,
        time_range_end=last + 60_000_000_000,
        bar_interval=Interval.minutes(1),
        initial_capital=10_000,
        fees=mbt.FeeConfig.zero(),          # costs would only blur the comparison
        slippage=Slippage.none(),
        warmup_bars=40,
        execution=mbt.ExecutionConfig(
            signal_delay=1, max_position_pct=1.0, allow_short=False,
            position_sizing_mode="FractionOfEquity",
        ),
    )


REASON = {0: "signal", 1: "stop", 2: "target", 3: "trailing", 4: "expiry"}


if __name__ == "__main__":
    root = tempfile.mkdtemp(prefix="mbt_ex27_")
    try:
        tape, store, frame = build_dataset(root)
    except PermissionError as exc:
        raise SystemExit(f"\n  {exc}\n") from None

    info = mbt.ticks.tape_info(tape)
    print(f"One tape: {info['n_trades']:,} trades over "
          f"{info['span_seconds'] / 3600:.1f} hours")
    print(f"Aggregated into {len(frame):,} bars of {BAR_SECONDS}s, "
          f"in the engine's canonical schema.\n")

    result = mbt.run(strategy, config_for(frame), store)
    trades = result.trades_df()
    bars = frame.set_index("timestamp")

    # -- Re-ask each bracket exit of the tape ---------------------------------
    # An exit is CONTESTED when its bar's range covered both levels: that is
    # exactly the bar on which the engine had to choose.
    entries = trades[trades["side"] == 1].reset_index(drop=True)
    exits = trades[trades["side"] == 2].reset_index(drop=True)

    disputed = []                            # (bar's verdict, sl, tp, entry data)
    for i in range(min(len(entries), len(exits))):
        entry_px = float(entries.loc[i, "fill_price"])
        reason = int(exits.loc[i, "exit_reason"])
        if reason not in (1, 2):            # only bracket exits are in question
            continue
        sl, tp = entry_px * (1 - SL_PCT / 100), entry_px * (1 + TP_PCT / 100)
        bar = bars.loc[exits.loc[i, "execution_timestamp"]]
        if bar["low"] <= sl and bar["high"] >= tp:
            disputed.append((reason, entry_px, sl, tp,
                             int(entries.loc[i, "execution_timestamp"].value)))

    # One call resolves them all: the tape is read once and every bracket is
    # replayed in parallel, in Rust. `entry=0` triggers on the first trade at
    # or after `start_times_ns[i]`: the entry is not re-simulated, it already
    # happened; only the race between the two levels is put to the tape.
    verdicts = mbt.ticks.simulate_brackets(
        tape,
        sides=["long"] * len(disputed),
        entries=[0.0] * len(disputed),
        sls=[d[2] for d in disputed],
        tps=[d[3] for d in disputed],
        start_times_ns=[d[4] for d in disputed],
    )

    contested, agreed, overturned, pnl_gap = len(disputed), 0, 0, 0.0
    for (reason, entry_px, sl, tp, _), truth in zip(disputed, verdicts):
        tape_reason = {"stop_loss": 1, "take_profit": 2}.get(truth["exit_reason"])
        if tape_reason == reason:
            agreed += 1
        elif tape_reason is not None:
            overturned += 1
            # The bar booked the stop; the tape says the target traded first.
            pnl_gap += (tp - sl) / entry_px

    bracket_exits = int(exits["exit_reason"].isin([1, 2]).sum())
    print(f"  {'bracket exits':<34}{bracket_exits:>8}")
    print(f"  {'of which the bar had to guess':<34}{contested:>8}"
          f"   ({contested / max(bracket_exits, 1):.0%})")
    print(f"  {'guessed right':<34}{agreed:>8}")
    print(f"  {'guessed wrong':<34}{overturned:>8}"
          f"   ({overturned / max(contested, 1):.0%} of the guesses)")
    print(f"\n  Those wrong guesses booked {pnl_gap:.1%} of return that the "
          f"trades\n  themselves never lost: each one recorded a "
          f"{SL_PCT:.1f}% stop where the\n  tape shows a {TP_PCT:.1f}% target.")
    print(f"  ({contested} contested exits is a small sample: read the sign of"
          f" the gap,\n  not its exact rate.)")

    print(f"\n  Reported result:  {result.metrics['total_return']:+.1%}   "
          f"({bracket_exits} bracket exits, "
          f"{contested} of them assumed rather than observed)")

    print("\n  The bars are not wrong, they are incomplete: a candle records")
    print("  where price went, never in what order. On a strategy whose exits")
    print("  sit inside single bars, that missing order IS the result.")
